<a href="https://colab.research.google.com/github/chiragdubey6299-cmd/Unified-Mentor-Python-Projects/blob/main/6_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [69]:
import numpy as np     # importing numpy library

In [70]:
A = np.array(5)        # Scalar Array
A

array(5)

In [71]:
np.ndim(A)               # Dimension method

0

In [72]:
One = np.array([1, 2, 3, 4, 5])
Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [73]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
Three.shape
np.ndim(Three)

3

In [75]:
np.ndim(One)
np.ndim(Two)
np.ndim(Three)

3

In [76]:

import numpy as np
one = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
two = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [77]:

Three = one.reshape(2, 2, 3)

In [78]:

np.ndim(one)
np.ndim(two)
np.ndim(Three)

3

# List vs Numpy Array

In [79]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [80]:
arr

array([1, 2, 3, 4, 5])

In [81]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [82]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [83]:

list1 = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])
print("Array division result:", arr/5)


Array division result: [0.2 0.4 0.6 0.8 1. ]


In [84]:

print(Three.shape)
print(Three.size)

(2, 2, 3)
12


# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



In [85]:

import time
import sys
size = 1000000
L = range(size)
A = np.arange(size)
start = time.time()
result_list = [(x**2 + x * 2) for x in L]
end = time.time()
print(f"Python List Time: {(end - start):.6f} seconds")
start = time.time()
result_array = (A**2 + A * 2)
end = time.time()
print(f"NumPy Array Time: {(end - start):.6f} seconds")
print(f"\nList memory: {sys.getsizeof(1) * size / 1024 / 1024:.2f} MB")
print(f"NumPy Array memory: {A.itemsize * A.size / 1024 / 1024:.2f} MB")

Python List Time: 0.172212 seconds
NumPy Array Time: 0.010608 seconds

List memory: 26.70 MB
NumPy Array memory: 7.63 MB


In [86]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original Array:", arr)
print("Original Shape:", arr.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)


In [87]:

arr_2d = arr.reshape(4, 3)
print("2D Reshaped Array:")
print(arr_2d)
print("New Shape:", arr_2d.shape)

2D Reshaped Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
New Shape: (4, 3)


# Reshaping arrays

Reshaping means changing the shape of an array.

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)


In [89]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [90]:

newarr = arr.reshape(2, 3, 2)


In [91]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [92]:

arr_flat = newarr.ravel()

print("Flattened Array:")
print(arr_flat)
print("Shape:", arr_flat.shape)

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)


In [93]:

arr_new_shape = arr.reshape(-1, 4)

print("Reshaped using -1 (3 rows, 4 columns):")
print(arr_new_shape)
print("Shape:", arr_new_shape.shape)

Reshaped using -1 (3 rows, 4 columns):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [94]:
# print(newarr)

In [95]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.vstack((a, b))
print("Vertically Stacked Array (vstack):")
print(c)

Vertically Stacked Array (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [96]:

d = np.hstack((a, b))
print("Horizontally Stacked Array (hstack):")
print(d)

Horizontally Stacked Array (hstack):
[[1 2 5 6]
 [3 4 7 8]]


# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [97]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [98]:
print(arr[0] + arr[1])                 # Addition of 2 elements

3


In [99]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

# print(arr[0, 3])                          # 1st row 4th element
# print(arr[1, 1])                          # 2nd row 5th element
print(arr[1,3])

9


In [100]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [101]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

arr3.shape
# print(arr3)
# print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column
# print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column
print(arr3[0,1,0])

4


In [102]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [103]:

slice1 = arr3[:, 0, :]
print("First Row of All Blocks:\n", slice1)
slice2 = arr3[1, :, :]
print("\nSecond Block (2D Matrix):\n", slice2)
slice3 = arr3[:, :, 1]
print("\nMiddle Column of All Blocks:\n", slice3)

First Row of All Blocks:
 [[1 2 3]
 [7 8 9]]

Second Block (2D Matrix):
 [[ 7  8  9]
 [10 11 12]]

Middle Column of All Blocks:
 [[ 2  5]
 [ 8 11]]
