<a href="https://colab.research.google.com/github/chiragdubey6299-cmd/Unified-Mentor-Python-Projects/blob/main/7_Advanced_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [78]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7])             # Slicing 1D Array

print(a1[1:5])     # Slicing                                  # [start:end]
print(a1[4])     # Indexing
a1[:4]

[2 3 4 5]
5


array([1, 2, 3, 4])

In [79]:
# print(a2)

In [80]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])      # Slicing 2D Array

a2[1, 1:4]                                            # [row:column]
a2[0:2, 2]
# a2[1:, :5]

array([3, 8])

In [81]:
a2.shape

(2, 5)

In [82]:
# a3.shape

In [83]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])           # # Slicing 3D Array

In [84]:
# a3[:2,1:,:2]                                                          # [matrix:row:column]

In [85]:
a3[:2,1:,:]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[23, 24, 25],
        [26, 27, 28]]])

In [86]:
# a3[:2,1:,:2]

In [87]:
import numpy as np
result_array = np.array([
    [[23, 24, 25],
     [26, 27, 28]],

    [[33, 34, 35],
     [36, 37, 38]]
])

print(result_array)

[[[23 24 25]
  [26 27 28]]

 [[33 34 35]
  [36 37 38]]]


In [88]:
# 'resuly array' की जगह 'resultarray' लिखें
resultarray = np.array([
    # ... array elements here
])

# View vs Copy

Copy is a new array, and the View is just a view of the original array.

Any changes made to the **copy** will not affect original array.

Any changes made to the **view** will affect the original array.

In [89]:
arr = np.array([1, 2, 3, 4, 5])

# Copy Method

copy = arr.copy()
copy[0] = 42

print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [90]:
arr = np.array([1, 2, 3, 4, 5])
copy = arr.copy()
copy[0] = 42
print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [91]:
# View Method

view = arr.view()
view[0] = 42

print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


In [92]:

view = arr.view()
view[0] = 42

print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


In [93]:

print("view.base is:")
print(view.base)


print("\ncopy.base is:")
print(copy.base)

view.base is:
[42  2  3  4  5]

copy.base is:
None


In [94]:

arr_slice_test = np.array([50, 60, 70, 80])
slice_view = arr_slice_test[1:3]

slice_view[0] = 600

print("\nAfter modifying the slice_view:")
print("arr_slice_test (Original):", arr_slice_test)
print("slice_view:", slice_view)


After modifying the slice_view:
arr_slice_test (Original): [ 50 600  70  80]
slice_view: [600  70]


# Append , Insert and Delete Operations

In [95]:
a = np.array([[1,2,3],
              [4,5,6]])
a.shape
# Append Method

np.append(a, [7,8,9])
np.append(a, [[7,8,9]],axis = 0)                # axis = 0 = row , axis = 1 = col
np.append(a, [[5],[8]],axis = 1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [96]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [97]:


print("Original Array 'a':\n", a)
c_delete_row = np.delete(a, 1, axis=0)
print("\nAfter np.delete(a, 1, axis=0) - Deleting Row 1:\n", c_delete_row)
c_delete_col = np.delete(a, 0, axis=1)
print("\nAfter np.delete(a, 0, axis=1) - Deleting Column 0:\n", c_delete_col)

Original Array 'a':
 [[1 2 3]
 [4 5 6]]

After np.delete(a, 1, axis=0) - Deleting Row 1:
 [[1 2 3]]

After np.delete(a, 0, axis=1) - Deleting Column 0:
 [[2 3]
 [5 6]]


In [98]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

# Insert Method

np.insert(a,3,[11,12])
np.insert(a,1,[11,12],axis = 0)
# np.insert(a,1,[11,12,13],axis = 1)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [99]:
print("Original Array 'a':\n", a)

# axis=0 (Row) पर Append करना: अब values में 2 items हैं जो array 'a' के 2 columns से मेल खाते हैं।
# [[7, 8]] का shape (1, 2) है।
a_appended_row = np.append(a, [[7, 8]], axis=0)

print("\nAfter np.append(a, [[7, 8]], axis=0) - Appending Row:\n", a_appended_row)

Original Array 'a':
 [[1 2]
 [3 4]
 [5 6]]

After np.append(a, [[7, 8]], axis=0) - Appending Row:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [100]:

print("Original Array 'a':\n", a)
a_deleted_row = np.delete(a, 1, axis=0)
print("\nAfter np.delete(a, 1, axis=0) - Deleting Row 1:\n", a_deleted_row)
a_deleted_col = np.delete(a, 0, axis=1)
print("\nAfter np.delete(a, 0, axis=1) - Deleting Column 0:\n", a_deleted_col)

Original Array 'a':
 [[1 2]
 [3 4]
 [5 6]]

After np.delete(a, 1, axis=0) - Deleting Row 1:
 [[1 2]
 [5 6]]

After np.delete(a, 0, axis=1) - Deleting Column 0:
 [[2]
 [4]
 [6]]


In [101]:
a = np.array([[ 1,  2,  3, 12],
              [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])

# Delete Method

# np.delete(a,4)
# np.delete(a,1,axis = 1)
np.delete(a,1,axis = 0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

In [102]:
# np.ndim(a)

In [103]:

print("Array Shape (Rows, Columns):", a.shape)
print("Array Size ):", a.size)

Array Shape (Rows, Columns): (3, 4)
Array Size ): 12


In [104]:

print(" Datatype:", a.dtype)
print(" Bytes:", a.itemsize)

 Datatype: int64
 Bytes: 8


# Hstack vs Vstack

Hstack is used to join two arrays **Horizontally**.

Vstack is used to join two arrays **Vertically**.


In [105]:
import numpy as np

In [106]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [107]:
print(a,b)
print(np.ndim(a), np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [108]:
# Performing Hstack

result = np.hstack((a,b))

print(result)
print(np.ndim(result))

[1 2 3 4 5 6]
1


In [109]:
# Performing Vstack

result = np.vstack((a,b))

print(result, np.ndim(result))

[[1 2 3]
 [4 5 6]] 2


In [110]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [111]:

result_stack_0 = np.stack((a, b), axis=0)
print("Stack (axis=0):\n", result_stack_0)
print("Dimension (ndim):", np.ndim(result_stack_0))
result_stack_1 = np.stack((a, b), axis=1)
print("\nStack (axis=1):\n", result_stack_1)
print("Dimension (ndim):", np.ndim(result_stack_1))

Stack (axis=0):
 [[1 2 3]
 [4 5 6]]
Dimension (ndim): 2

Stack (axis=1):
 [[1 4]
 [2 5]
 [3 6]]
Dimension (ndim): 2


In [112]:

c = np.array([1, 2, 3, 4, 5, 6])
print("Original Array 'c':", c)
result_split_equal = np.split(c, 3)
print("\nSplit into 3 equal parts:", result_split_equal)
result_split_unequal = np.split(c, [2, 5])
print("\nSplit at indices [2, 5]:", result_split_unequal)

Original Array 'c': [1 2 3 4 5 6]

Split into 3 equal parts: [array([1, 2]), array([3, 4]), array([5, 6])]

Split at indices [2, 5]: [array([1, 2]), array([3, 4, 5]), array([6])]


# Numpy Concatenation

It is used for joining two or more arrays of the same shape along a specified axis.

Axis = 0, Adding new rows

Axis = 1, Adding new columns


In [113]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

# print(arr1.shape,arr2.shape)

arr3 = np.array([[3], [9]])
arr4 = np.array([[4] , [8]])

print(arr3.shape,arr4.shape)

new = np.concatenate((arr1, arr2), axis = 0)

# print(new, new.shape)

(2, 1) (2, 1)


In [114]:
new = np.concatenate((arr3, arr4), axis = 1)

print(new)

[[3 4]
 [9 8]]


In [115]:
arr3 = np.array([[3], [9]])
arr4 = np.array([[4], [8]])

In [116]:

hstack_result = np.hstack((arr3, arr4))

print("np.hstack(arr3, arr4):")
print(hstack_result)
print("\nNew Array Shape:", hstack_result.shape)

np.hstack(arr3, arr4):
[[3 4]
 [9 8]]

New Array Shape: (2, 2)
