# <center> Numpy Basics </center>

In [165]:
import pandas as pd
import numpy as np



We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [166]:
a = pd.Series([100, 200, 300, 400])



In [167]:
print(a)
print(type(a))



0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [168]:
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [169]:
print(f"a ndim: {a.ndim}")
print(f"b ndim: {b.ndim}")
print(f"c ndim: {c.ndim}")
print(f"d ndim: {d.ndim}")





a ndim: 0
b ndim: 1
c ndim: 2
d ndim: 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [170]:
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
print(f"c shape: {c.shape}")
print(f"d shape: {d.shape}")






a shape: ()
b shape: (3,)
c shape: (2, 3)
d shape: (1, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [171]:
print(f"c dtype: {c.dtype}")
print(f"d dtype: {d.dtype}")





c dtype: int64
d dtype: int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [172]:
print(type(a))
print(type(b))






<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [173]:
print(len(b))

3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy. 

In [174]:
print(len(b))

3


Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [175]:
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)
print(f"l3: {l3}")
print(f"l4: {l4}")

l3: [10 20 30]
l4: [40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [176]:

%timeit [l1[i] * l2[i] for i in range(len(l1))]




KeyboardInterrupt: 

Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:

%timeit l3 * l4



584 ns ± 60.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
x = np.arange(1, 11)
print(x)


[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
x_step = np.arange(1, 11, 2)
print(x_step)




[1 3 5 7 9]


identity_matrix = np.eye(3)
print(identity_matrix)




In [ ]:
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])


In [ ]:
x = np.arange(1, 17)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
x_reshaped = x.reshape(2, 8)
print(x_reshaped)



[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:

x_3d = x.reshape(2, 4, 2)
print(x_3d)




[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:

x_4x4 = x.reshape(4, -1)
print(x_4x4)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:

y = x.reshape(2, 4, -1)
print(y)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
y_flattened = y.flatten()
print(y_flattened)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
a = np.arange(2, 17, 2)
print(a)

[ 2  4  6  8 10 12 14 16]


In [ ]:

print(a[2])


6


In [ ]:

import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])




[ 10  20  30  40  50  60  70  80  90 100]


Lets check the same for 2 D array

In [ ]:

print(arr.ndim)


1


In [ ]:
'
print(a[2, 2])



SyntaxError: unterminated string literal (detected at line 1) (1442818297.py, line 1)

Well done!

Now lets check indexing for 3 D array 

In [ ]:

b = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[7, 8, 9], [10, 11, 12]]])

print(b)
print("Shape of b:", b.shape)
print("Dimension of b:", b.ndim)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of b: (2, 2, 3)
Dimension of b: 3


In [ ]:


print(b[0, 1, 2])




6


In [ ]:

import numpy as np 

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(arr)




[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:

print(arr[0:5])





[10 20 30 40 50]


Note: The result includes the start index, but excludes the end index.



In [ ]:

print(arr[5:])


[ 60  70  80  90 100]


In [ ]:

print(arr[:5])





[10 20 30 40 50]


**STEP**

Use the step value to determine the step of the slicing:

In [ ]:

print(arr[1:7:2])




[20 40 60]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:

print(arr[::2])




[10 30 50 70 90]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [ ]:

print(a)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:

print(a[2, 1:5])




[8 9]


In [ ]:

print(a[:, 2])




[ 3  6  9 12]


In [ ]:

print(a[:, 1:])




[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [ ]:

x1 = np.array([10, 20, 30, 40, 50])

print("Original array x1:", x1)



Original array x1: [10 20 30 40 50]


In [ ]:

x2 = x1.view()

print("View array x2:", x2)



View array x2: [10 20 30 40 50]


In [ ]:

print("x1:", x1)
print("x2:", x2)




x1: [10 20 30 40 50]
x2: [10 20 30 40 50]


Ok now you have seen that both of them are same 

In [ ]:

x2[0] = 99
print("x2 changed to:", x2)




x2 changed to: [99 20 30 40 50]


In [ ]:

print("x1 (after change in x2):", x1)
print("x2 (after change in x2):", x2)



x1 (after change in x2): [99 20 30 40 50]
x2 (after change in x2): [99 20 30 40 50]


In [ ]:

print("x1.base is:", x1.base)
print("x2.base is:", x2.base)
print("Is x2 a view of x1? (x2.base is x1):", x2.base is x1)



x1.base is: None
x2.base is: [99 20 30 40 50]
Is x2 a view of x1? (x2.base is x1): True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [ ]:

x3 = x1.view()

print("x3 (View of x1):", x3)


x3 (View of x1): [99 20 30 40 50]


In [ ]:

x3[0] = 999
print("x1 (after change in x3):", x1)
print("x3 (after change in x3):", x3)




x1 (after change in x3): [999  20  30  40  50]
x3 (after change in x3): [999  20  30  40  50]


Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [ ]:

x3[0] = 100

print("x3 updated:", x3)



x3 updated: [100  20  30  40  50]


In [ ]:

print("x1 (Original array after change in x3):", x1)
print("x3 (View array):", x3)




x1 (Original array after change in x3): [100  20  30  40  50]
x3 (View array): [100  20  30  40  50]


Now its proved.

Lets see how **Copy()** function works

In [ ]:

x4 = x1.copy()

print("x4 (Copy of x1):", x4)



x4 (Copy of x1): [100  20  30  40  50]


In [ ]:

x4[-1] = 999

print("x4 updated:", x4)





x4 updated: [100  20  30  40 999]


In [ ]:

print("x1 (Original array after change in x4):", x1)
print("x4 (Copy array):", x4)





x1 (Original array after change in x4): [100  20  30  40  50]
x4 (Copy array): [100  20  30  40 999]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [ ]:

print("x1.base is:", x1.base)
print("x4.base is:", x4.base)
print("Are x1 and x4 the same object? (x1 is x4):", x1 is x4)




x1.base is: None
x4.base is: None
Are x1 and x4 the same object? (x1 is x4): False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [ ]:

print(np.hstack((x1, x4)))



[100  20  30  40  50 100  20  30  40 999]


In [ ]:

print(np.vstack((x1, x4)))



[[100  20  30  40  50]
 [100  20  30  40 999]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [ ]:

import numpy as np 
arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])

print("arr1:\n", arr1)
print("arr2:\n", arr2)



arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]


In [ ]:

result_rows = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenate along rows (axis=0):\n", result_rows)




Concatenate along rows (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [ ]:

result_cols = np.concatenate((arr1, arr2), axis=1)
print("Concatenate along columns (axis=1):\n", result_cols)



Concatenate along columns (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


Lets use insert() function which Inserts values into array before specified index value

In [ ]:

result = np.insert(x1, 4, x4)
print(result)



[100  20  30  40 100  20  30  40 999  50]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:

x2_deleted = np.delete(x2, 1)

print(x2_deleted)




[100  30  40  50]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner! 

In [ ]:

print("Sum of x1:", np.sum(x1))
print("Cumulative Sum of x1:", np.cumsum(x1))

Sum of x1: 240
Cumulative Sum of x1: [100 120 150 190 240]
